name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Bundle
        run: deno task bundle

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "justinawrey-chip8"
          entrypoint: https://deno.land/std/http/file_server.ts
          root: static
